# Chapter 7

In [2]:
import pandas as pd
import numpy as np

In [3]:
string_data = pd.Series(['aardvark', 'artichoke',np.nan, 'avocado'])

In [4]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [5]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
string_data[0] = None

In [7]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [8]:
from numpy import nan as NA

In [9]:
data = pd.Series([1,NA,3.5,NA,7])

In [11]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [12]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [13]:
data = pd.DataFrame([[1.,6.5,3.],[1.,NA,NA],[NA,NA,NA],[NA,6.5,3.]])

In [15]:
cleaned = data.dropna()

In [16]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [18]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [20]:
data[4] = NA

In [21]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [22]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [23]:
np.random.randn(7,3)

array([[-1.24284046, -0.51084869,  0.37578561],
       [ 1.37339158,  0.90196902,  0.73883066],
       [ 1.67803295, -1.44862668,  0.67907922],
       [ 0.08052634,  0.43763554, -1.25546206],
       [-0.64184538,  0.53989227, -0.35677786],
       [-0.16780777,  0.1892412 ,  1.17878097],
       [ 0.54746675, -0.39929659, -1.09375216]])

In [24]:
df = pd.DataFrame(np.random.randn(7,3))

In [25]:
df.iloc[:4, 1] = NA

In [26]:
df

0         1         2
0 -1.334844       NaN -0.067407
1  0.705066       NaN -2.394082
2  1.589104       NaN -0.653829
3 -1.109080       NaN -1.285222
4  1.236909  0.650261  0.008210
5  0.330897 -1.975941  0.855045
6  0.596046 -0.021453 -0.315836

In [27]:
df.iloc[:2, 2] = NA

In [28]:
df

0         1         2
0 -1.334844       NaN       NaN
1  0.705066       NaN       NaN
2  1.589104       NaN -0.653829
3 -1.109080       NaN -1.285222
4  1.236909  0.650261  0.008210
5  0.330897 -1.975941  0.855045
6  0.596046 -0.021453 -0.315836

In [29]:
df.dropna()

0         1         2
4  1.236909  0.650261  0.008210
5  0.330897 -1.975941  0.855045
6  0.596046 -0.021453 -0.315836

In [33]:
df.dropna(thresh=2)

0         1         2
2  1.589104       NaN -0.653829
3 -1.109080       NaN -1.285222
4  1.236909  0.650261  0.008210
5  0.330897 -1.975941  0.855045
6  0.596046 -0.021453 -0.315836

In [34]:
df.fillna(0)

0         1         2
0 -1.334844  0.000000  0.000000
1  0.705066  0.000000  0.000000
2  1.589104  0.000000 -0.653829
3 -1.109080  0.000000 -1.285222
4  1.236909  0.650261  0.008210
5  0.330897 -1.975941  0.855045
6  0.596046 -0.021453 -0.315836

In [35]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -1.334844  0.500000  0.000000
1  0.705066  0.500000  0.000000
2  1.589104  0.500000 -0.653829
3 -1.109080  0.500000 -1.285222
4  1.236909  0.650261  0.008210
5  0.330897 -1.975941  0.855045
6  0.596046 -0.021453 -0.315836

In [36]:
_ = df.fillna(0, inplace=True)

In [37]:
df

0         1         2
0 -1.334844  0.000000  0.000000
1  0.705066  0.000000  0.000000
2  1.589104  0.000000 -0.653829
3 -1.109080  0.000000 -1.285222
4  1.236909  0.650261  0.008210
5  0.330897 -1.975941  0.855045
6  0.596046 -0.021453 -0.315836

In [38]:
df = pd.DataFrame(np.random.randn(6,3))

In [39]:
df.iloc[2:,1] = NA

In [40]:
df.iloc[4:,2] = NA

In [41]:
df

0        1         2
0 -0.657253 -0.09949  0.808949
1 -1.334725 -1.13400  1.179417
2  0.663352      NaN  0.479577
3 -3.119350      NaN -1.059744
4  0.219031      NaN       NaN
5  0.466651      NaN       NaN

In [42]:
df.fillna(method='ffill')

0        1         2
0 -0.657253 -0.09949  0.808949
1 -1.334725 -1.13400  1.179417
2  0.663352 -1.13400  0.479577
3 -3.119350 -1.13400 -1.059744
4  0.219031 -1.13400 -1.059744
5  0.466651 -1.13400 -1.059744

In [43]:
df.fillna(method='ffill', limit=2)

0        1         2
0 -0.657253 -0.09949  0.808949
1 -1.334725 -1.13400  1.179417
2  0.663352 -1.13400  0.479577
3 -3.119350 -1.13400 -1.059744
4  0.219031      NaN -1.059744
5  0.466651      NaN -1.059744

In [44]:
data = pd.Series([1.,NA,3.5,NA,7])

In [45]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

7.2

In [46]:
data = pd.DataFrame({'k1':['one','two'] * 3 + ['two'],
                     'k2':[1,1,2,3,3,4,4]})

In [47]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [48]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [49]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [50]:
data['v1'] = range(7)

In [51]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [52]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [53]:
data.drop_duplicates(['k1','k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [54]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon','Pastrami', 'corned beef', 'Bacon','pastrami', 'honey ham', 'nova lox'],
                     'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [55]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [56]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

In [57]:
lowercased = data['food'].str.lower()

In [58]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [59]:
data['animal'] = lowercased.map(meat_to_animal)

In [60]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [61]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [62]:
data = pd.Series([1., -999.,2.,-999.,-1000.,3.])

In [63]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [64]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [65]:
data.replace([-999.,-1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [67]:
data.replace([-999,-1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [68]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [71]:
data = pd.DataFrame(np.arange(12).reshape(3,4), index=['Ohio','Colorado','New York'], columns=['one','two','three','four'])

In [72]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [73]:
transform = lambda x:x[:4].upper()

In [74]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [75]:
data.index = data.index.map(transform)

In [76]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [77]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [78]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [79]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [80]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [81]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [83]:
bins=[18, 25, 35, 60, 100]

In [84]:
cats = pd.cut(ages, bins)

In [85]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [86]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [87]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [88]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [89]:
pd.cut(ages,[18,26,36,61,100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [90]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [91]:
group_names = ['Youth','YoungAdult','MiddleAged','Senior']

In [93]:
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [94]:
data = np.random.rand(20)

In [95]:
pd.cut(data, 4, precision=2)

[(0.29, 0.52], (0.52, 0.75], (0.75, 0.98], (0.75, 0.98], (0.52, 0.75], ..., (0.75, 0.98], (0.29, 0.52], (0.52, 0.75], (0.52, 0.75], (0.52, 0.75]]
Length: 20
Categories (4, interval[float64]): [(0.067, 0.29] < (0.29, 0.52] < (0.52, 0.75] < (0.75, 0.98]]

In [96]:
data = np.random.randn(1000)

In [97]:
cats = pd.qcut(data,4)

In [98]:
cats

[(-0.0165, 0.624], (-2.907, -0.743], (-0.0165, 0.624], (-0.0165, 0.624], (-2.907, -0.743], ..., (-0.0165, 0.624], (-0.0165, 0.624], (0.624, 3.492], (0.624, 3.492], (-0.743, -0.0165]]
Length: 1000
Categories (4, interval[float64]): [(-2.907, -0.743] < (-0.743, -0.0165] < (-0.0165, 0.624] < (0.624, 3.492]]

In [99]:
pd.value_counts(cats)

(0.624, 3.492]       250
(-0.0165, 0.624]     250
(-0.743, -0.0165]    250
(-2.907, -0.743]     250
dtype: int64

In [100]:
pd.qcut(data, [0,0.1,0.5,0.9,1.])

[(-0.0165, 1.189], (-1.451, -0.0165], (-0.0165, 1.189], (-0.0165, 1.189], (-1.451, -0.0165], ..., (-0.0165, 1.189], (-0.0165, 1.189], (1.189, 3.492], (-0.0165, 1.189], (-1.451, -0.0165]]
Length: 1000
Categories (4, interval[float64]): [(-2.907, -1.451] < (-1.451, -0.0165] < (-0.0165, 1.189] < (1.189, 3.492]]

In [101]:
data = pd.DataFrame(np.random.randn(1000,4))

In [102]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.041475     0.034196    -0.045120    -0.018538
std       0.975952     1.033883     1.007428     0.978590
min      -3.237320    -4.853536    -3.467906    -3.372106
25%      -0.680326    -0.639553    -0.740375    -0.652451
50%      -0.037278     0.036464    -0.061437    -0.014894
75%       0.647551     0.726353     0.600670     0.623548
max       3.265639     3.678997     3.235952     3.235825

In [107]:
col =data[2]

In [108]:
col[np.abs(col)>3]

346    3.235952
433   -3.072795
647   -3.467906
874    3.031821
Name: 2, dtype: float64

In [116]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
8    1.427677  3.678997 -0.287599 -0.958399
75   0.488398  3.031829  1.535171 -0.039243
180  0.659373 -0.995039 -0.114025  3.235825
195  1.405494 -4.853536 -0.232434 -1.256187
315 -3.237320 -0.922084  2.040826  0.033549
346 -0.951912  0.478821  3.235952 -0.506932
363  0.589967 -0.093698  0.753953  3.012872
396 -3.085851  1.285693  0.591622 -1.327187
433 -0.391247 -0.386420 -3.072795 -0.908401
569 -0.796793  0.653943  0.322628 -3.372106
595  1.297321 -3.773321  1.641870  0.719929
647 -0.533630  0.470570 -3.467906  0.657680
874 -0.812922  0.073954  3.031821 -1.776381
936  3.265639 -1.573272  0.427555  0.612084

In [112]:
data

0         1         2         3
0    0.793932 -0.704774  0.953047  0.092552
1    1.241899  1.081340  0.479936 -1.929524
2    0.700941 -0.206738 -1.147549 -2.528929
3    1.005671  0.852944  1.965718  0.917725
4   -0.730588 -0.622816 -0.290814  0.843985
..        ...       ...       ...       ...
995 -1.899483 -2.400122 -0.221931  2.381819
996 -0.895111 -0.433612  0.283206 -0.315799
997  0.252654 -0.741300 -0.623143  0.211987
998 -0.221491 -2.127074  0.362345  0.069308
999 -0.771565  0.199597  0.498591  1.963970

[1000 rows x 4 columns]

In [117]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [119]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.041417     0.036112    -0.044847    -0.018415
std       0.974073     1.021878     1.004887     0.976586
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.680326    -0.639553    -0.740375    -0.652451
50%      -0.037278     0.036464    -0.061437    -0.014894
75%       0.647551     0.726353     0.600670     0.623548
max       3.000000     3.000000     3.000000     3.000000

In [120]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0  1.0  1.0
1  1.0  1.0  1.0 -1.0
2  1.0 -1.0 -1.0 -1.0
3  1.0  1.0  1.0  1.0
4 -1.0 -1.0 -1.0  1.0

In [121]:
df = pd.DataFrame(np.arange(5*4).reshape(5,4))

In [122]:
sampler = np.random.permutation(5)

In [123]:
sampler

array([4, 3, 2, 1, 0])

In [124]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [125]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
3  12  13  14  15
2   8   9  10  11
1   4   5   6   7
0   0   1   2   3

In [126]:
df.sample(n=3)

0   1   2   3
1   4   5   6   7
4  16  17  18  19
0   0   1   2   3

In [127]:
choices = pd.Series([5,7,-1,6,4])

In [128]:
draws = choices.sample(n=10, replace =True)

In [129]:
draws

2   -1
2   -1
4    4
4    4
2   -1
3    6
1    7
4    4
2   -1
1    7
dtype: int64

In [130]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})

In [131]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [132]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [133]:
dummies = pd.get_dummies(df['key'], prefix = 'key')

In [134]:
df_with_dummy = df[['data1']].join(dummies)

In [135]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [136]:
mnames=['movie_id', 'title','genres']

In [137]:
movies = pd.read_table('examples/movielens/movies.dat', sep='::', header=None, names = mnames)

<ipython-input-137-2f53f9b1b45a>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  movies = pd.read_table('examples/movielens/movies.dat', sep='::', header=None, names = mnames)


In [138]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [139]:
all_genres =[]

In [141]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [143]:
genres = pd.unique(all_genres)

In [144]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [145]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [146]:
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [147]:
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
1           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
2           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
4           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3878        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3879        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3880        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3881        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3882        0.0         0.0     0.0        0.0      0.0      0.0    0.0   

      Action  Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  \
0        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
1        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
2        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
4        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
...      ...    ...       ...     ...     ...          ...  ...      ...   
3878     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3879     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3880     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3881     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3882     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   

      Mystery  Film-Noir  Western  
0         0.0        0.0      0.0  
1         0.0        0.0      0.0  
2         0.0        0.0      0.0  
3         0.0        0.0      0.0  
4         0.0        0.0      0.0  
...       ...        ...      ...  
3878      0.0        0.0      0.0  
3879      0.0        0.0      0.0  
3880      0.0        0.0      0.0  
3881      0.0        0.0      0.0  
3882      0.0        0.0      0.0  

[3883 rows x 18 columns]

In [148]:
gen = movies.genres[0]

In [149]:
gen

"Animation|Children's|Comedy"

In [150]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [151]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [163]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    print(indices)
    dummies.iloc[i, indices] = 1

[0 1 2]
[3 1 4]
[2 5]
[2 6]
[2]
[7 8 9]
[2 5]
[3 1]
[7]
[7 3 9]
[2 6 5]
[ 2 10]
[0 1]
[6]
[7 3 5]
[6 9]
[6 5]
[9]
[2]
[7]
[7 2 6]
[8 6 9]
[9]
[ 6 11]
[6 5]
[6]
[6]
[5]
[ 3 11]
[6]
[6]
[ 6 11]
[3 5]
[1 2 6]
[6 5]
[6]
[12]
[2]
[2 5]
[6]
[ 6 13]
[7 8 6]
[6]
[7 3]
[2 6]
[6 5]
[8 9]
[ 0  1 14  5]
[6 5]
[8 9]
[7 6 9]
[2]
[6]
[1 2]
[6]
[3 1 4]
[6]
[6 5]
[ 6 15]
[3 1 4]
[6 9]
[6]
[2]
[2 5]
[2]
[11  9]
[6]
[2 5]
[2]
[ 7  2  8 10  9]
[7]
[2 6]
[ 6 14]
[6 5]
[2 6]
[11  9]
[12]
[6]
[6 9]
[6]
[8 6 5]
[6]
[6]
[2 6]
[6 5]
[3 6]
[1 2]
[2]
[7 9]
[6]
[6 9]
[2 5]
[6]
[7 9]
[2]
[6]
[7 9]
[12]
[6 9]
[2]
[2]
[9]
[2]
[6 5]
[2 6]
[ 3  1  2 14]
[12]
[2]
[ 7  6 13]
[6 9]
[7 3 8]
[ 6 15]
[6]
[2]
[12]
[8]
[2 5]
[2]
[6]
[6]
[2 5]
[ 6 15  5]
[6]
[2]
[3 1 4]
[6]
[12]
[2 5]
[6]
[6 5]
[9]
[2 6]
[12]
[2]
[12]
[12]
[6]
[7 6]
[6 5]
[2]
[6]
[6]
[2]
[7]
[3 1]
[6]
[6]
[8 6 9]
[6]
[ 6  5 13]
[10]
[7 3 2 8]
[6]
[ 6 13]
[2]
[ 2 13]
[3 1]
[6]
[ 7  3 15 11]
[ 6  9 13]
[12]
[7 5 9]
[ 8 16 15  9]
[7 9]
[2 6]
[6]
[7 3 6 5]
[3 1 6]


[6 9]
[15]
[2]
[6]
[ 6 14]
[ 7  6  9 13]
[ 0  1 14]
[2]
[5]
[2]
[7 3 1]
[6 5]
[7]
[6 5]
[7 3 9]
[2 8]
[8]
[5]
[2]
[6]
[ 6 13]
[6]
[6]
[6]
[2]
[2]
[5]
[6 9]
[2]
[2]
[7 9]
[6]
[5]
[6]
[7 8 5]
[6]
[7 3 1 4]
[2]
[ 7 11]
[2]
[6]
[6]
[2]
[6]
[6]
[6 5]
[2]
[3 1]
[2 8]
[2 5]
[2 6 5]
[6]
[ 7  3 11  9]
[6]
[2]
[1 6]
[6]
[6 5]
[2 5]
[3 1 6]
[7 3 9]
[2]
[6 5]
[6]
[7 5 9]
[6]
[2]
[6]
[2]
[7 3 8]
[6]
[2 5]
[2 9]
[ 3  0  1  2 14]
[6]
[ 8  6 15]
[2 5]
[11]
[2 5]
[6]
[ 7 11  9]
[5]
[6]
[6]
[8]
[6]
[ 7  3  2 11]
[2]
[3 1]
[1 4]
[ 6 11]
[2]
[ 7  6 13]
[7 3]
[1 2]
[ 8  6 15]
[ 7 15 11  9]
[ 7  3 11  9]
[1 2]
[2 5]
[6]
[3 1 6]
[6]
[ 7 15  5  9]
[8 6 9]
[7]
[6 5]
[ 8  6 16]
[2]
[11  9]
[7 2]
[3 5]
[7 3]
[7 9]
[6]
[7 9]
[6]
[2]
[6]
[2]
[3 9]
[ 7  9 13]
[ 8 16 15  9]
[ 6 13]
[8 6 9]
[6]
[2 6]
[10]
[6]
[15  9]
[7 6 9]
[ 7  8 15]
[6]
[2 5]
[2 6]
[9]
[2 5]
[6]
[6]
[7 9]
[6 5]
[2]
[2]
[2 6]
[6 5]
[10 15  9]
[ 8 10 15  9]
[2]
[8 9]
[2 6 9]
[12]
[6]
[6]
[12]
[ 6 11  9]
[1 6 4]
[10]
[5]
[12]
[5 9]
[6]
[6]
[9]
[8]
[2

[6]
[7 3]
[6 5]
[2]
[6]
[12]
[6 5]
[6]
[7 8 6]
[2]
[2 6]
[2]
[ 7  3 11  9]
[8 9]
[2]
[6 5]
[6 5]
[17]
[17]
[2]
[7 2]
[6]
[2 6]
[6 5]
[6]
[6]
[12]
[6]
[6]
[6]
[14]
[2 5]
[2]
[2]
[6]
[6 9]
[16]
[14  5 13]
[6 5]
[6 5]
[ 7 13]
[15]
[ 2 14]
[7]
[7]
[7]
[3 6 5]
[ 7 17]
[8 9]
[1 2]
[6]
[6]
[7 8 9]
[6]
[6]
[6]
[6]
[2 6]
[2 5]
[8 6]
[6]
[7]
[6]
[6 9]
[ 3  4 11]
[6 5]
[3 6]
[14]
[ 6 13]
[2]
[10  9]
[6]
[ 6 10]
[2 6]
[2 5]
[6]
[6]
[12]
[10  9]
[9]
[12]
[ 7  8 11]
[ 7  8 11]
[ 3  0 16]
[6]
[7]
[7]
[7]
[10  9]
[7]
[6]
[10]
[6]
[2]
[5]
[2]
[7 3 0]
[6]
[12]
[2 6]
[2 5]
[9]
[6]
[12]
[9]
[6]
[6]
[6]
[2]
[ 2 10]
[2]
[9]
[10]
[10]
[10]
[8 6]
[7 6]
[10]
[2]
[2 5]
[10 11]
[17]
[10]
[10]
[2]
[7 6]
[ 2  6 17]
[2]
[11]
[ 2 11]
[0 1]
[ 2  6 13]
[3]
[ 2  6 17]
[6]
[2]
[2]
[2]
[2]
[2]
[15  5  9]
[2 6]
[2 5]
[6]
[2]
[ 2 13]
[6]
[6]
[2]
[ 6 13]
[0 1]
[9]
[9]
[2]
[10 11]
[6]
[2 6]
[ 2 14]
[ 7  6 13]
[9]
[9]
[6]
[13]
[2 6]
[6]
[6]
[ 3  2 11]
[6]
[2]
[6 5]
[17]
[9]
[2]
[12]
[6]
[6]
[ 6 11]
[10  5]
[7 9]
[2 6]
[12]
[1

In [153]:
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           1.0         1.0     1.0        0.0      0.0      0.0    0.0   
1           0.0         1.0     0.0        1.0      1.0      0.0    0.0   
2           0.0         0.0     1.0        0.0      0.0      1.0    0.0   
3           0.0         0.0     1.0        0.0      0.0      0.0    1.0   
4           0.0         0.0     1.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3878        0.0         0.0     1.0        0.0      0.0      0.0    0.0   
3879        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3880        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3881        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3882        0.0         0.0     0.0        0.0      0.0      0.0    1.0   

      Action  Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  \
0        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
1        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
2        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
4        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
...      ...    ...       ...     ...     ...          ...  ...      ...   
3878     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3879     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3880     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3881     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3882     0.0    0.0       1.0     0.0     0.0          0.0  0.0      0.0   

      Mystery  Film-Noir  Western  
0         0.0        0.0      0.0  
1         0.0        0.0      0.0  
2         0.0        0.0      0.0  
3         0.0        0.0      0.0  
4         0.0        0.0      0.0  
...       ...        ...      ...  
3878      0.0        0.0      0.0  
3879      0.0        0.0      0.0  
3880      0.0        0.0      0.0  
3881      0.0        0.0      0.0  
3882      0.0        0.0      0.0  

[3883 rows x 18 columns]

In [154]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [156]:
movies_windic

movie_id                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
3878      3948             Meet the Parents (2000)   
3879      3949          Requiem for a Dream (2000)   
3880      3950                    Tigerland (2000)   
3881      3951             Two Family House (2000)   
3882      3952               Contender, The (2000)   

                            genres  Genre_Animation  Genre_Children's  \
0      Animation|Children's|Comedy              1.0               1.0   
1     Adventure|Children's|Fantasy              0.0               1.0   
2                   Comedy|Romance              0.0               0.0   
3                     Comedy|Drama              0.0               0.0   
4                           Comedy              0.0               0.0   
...                            ...              ...               ...   
3878                        Comedy              0.0               0.0   
3879                         Drama              0.0               0.0   
3880                         Drama              0.0               0.0   
3881                         Drama              0.0               0.0   
3882                Drama|Thriller              0.0               0.0   

      Genre_Comedy  Genre_Adventure  Genre_Fantasy  Genre_Romance  \
0              1.0              0.0            0.0            0.0   
1              0.0              1.0            1.0            0.0   
2              1.0              0.0            0.0            1.0   
3              1.0              0.0            0.0            0.0   
4              1.0              0.0            0.0            0.0   
...            ...              ...            ...            ...   
3878           1.0              0.0            0.0            0.0   
3879           0.0              0.0            0.0            0.0   
3880           0.0              0.0            0.0            0.0   
3881           0.0              0.0            0.0            0.0   
3882           0.0              0.0            0.0            0.0   

      Genre_Drama  ...  Genre_Crime  Genre_Thriller  Genre_Horror  \
0             0.0  ...          0.0             0.0           0.0   
1             0.0  ...          0.0             0.0           0.0   
2             0.0  ...          0.0             0.0           0.0   
3             1.0  ...          0.0             0.0           0.0   
4             0.0  ...          0.0             0.0           0.0   
...           ...  ...          ...             ...           ...   
3878          0.0  ...          0.0             0.0           0.0   
3879          1.0  ...          0.0             0.0           0.0   
3880          1.0  ...          0.0             0.0           0.0   
3881          1.0  ...          0.0             0.0           0.0   
3882          1.0  ...          0.0             1.0           0.0   

      Genre_Sci-Fi  Genre_Documentary  Genre_War  Genre_Musical  \
0              0.0                0.0        0.0            0.0   
1              0.0                0.0        0.0            0.0   
2              0.0                0.0        0.0            0.0   
3              0.0                0.0        0.0            0.0   
4              0.0                0.0        0.0            0.0   
...            ...                ...        ...            ...   
3878           0.0                0.0        0.0            0.0   
3879           0.0                0.0        0.0            0.0   
3880           0.0                0.0        0.0            0.0   
3881           0.0                0.0        0.0            0.0   
3882           0.0                0.0        0.0            0.0   

      Genre_Myste

In [164]:
np.random.seed(12345)

In [165]:
values = np.random.rand(10)

In [166]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [167]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [168]:
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

7.3


In [171]:
val = 'a,b,   guido'

In [172]:
val.split(',')

['a', 'b', '   guido']

In [173]:
pieces = [x.strip() for x in val.split(',')]

In [174]:
pieces

['a', 'b', 'guido']

In [175]:
first, second, third = pieces

In [176]:
first + '::' + second + '::' + third

'a::b::guido'

In [177]:
'::'.join(pieces)

'a::b::guido'

In [178]:
'guido' in val

True

In [179]:
val.index(',')

1

In [180]:
val.find(':')

-1

In [181]:
val.index(':')

ValueError: substring not found

In [182]:
val

'a,b,   guido'

In [183]:
val.count(',')

2

In [184]:
val.replace(',','::')

'a::b::   guido'

In [185]:
val.replace(',','')

'ab   guido'

In [186]:
import re

In [187]:
text = "foo bar\t baz \tqux"

In [188]:
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [189]:
regex = re.compile('\s+')

In [190]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [191]:
regex.findall(text)

[' ', '\t ', ' \t']

In [192]:
text = """Dave dave@google.com
steve steve@gmail.com
rob rob@gmail.com
ryan ryan@yahoo.com
"""

pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [194]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [195]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [196]:
m = regex.search(text)

In [197]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [198]:
text[m.start():m.end()]

'dave@google.com'

In [200]:
print(regex.match(text))

None


In [201]:
print(regex.sub('REDACTED', text))

Dave REDACTED
steve REDACTED
rob REDACTED
ryan REDACTED



In [202]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [203]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [204]:
m = regex.match('wesm@bright.net')

In [205]:
m.groups()

('wesm', 'bright', 'net')

In [206]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [208]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
steve Username: steve, Domain: gmail, Suffix: com
rob Username: rob, Domain: gmail, Suffix: com
ryan Username: ryan, Domain: yahoo, Suffix: com



In [209]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@google.com', 'Rob': 'rob@gmail.com', 'Wes': np.nan}

In [210]:
data = pd.Series(data)

In [211]:
data

Dave      dave@google.com
Steve    steve@google.com
Rob         rob@gmail.com
Wes                   NaN
dtype: object

In [212]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [213]:
data.str.contains('gmail')

Dave     False
Steve    False
Rob       True
Wes        NaN
dtype: object

In [214]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave      [(dave, google, com)]
Steve    [(steve, google, com)]
Rob         [(rob, gmail, com)]
Wes                         NaN
dtype: object

In [215]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [216]:
matches

Dave      (dave, google, com)
Steve    (steve, google, com)
Rob         (rob, gmail, com)
Wes                       NaN
dtype: object

In [217]:
matches.str.get(1)

Dave     google
Steve    google
Rob       gmail
Wes         NaN
dtype: object

In [218]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [220]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve  google  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN